### ISSUE TITLE
Return code is always 0 - even in case of error

### ISSUE THREAD

**Issue by xurei** [auth0/auth0-deploy-cli#2]
When I run a0deploy with a configuration that is incorrect, a0deploy returns 0. It should return an error code instead.

By returning 0 every time, pipelining tools won't stop if the deployment failed.

**Comment by mostekcm** [comment]
Great point. Will get this in.

**Comment by mostekcm** [comment]
Once I have this PR merged and released, I can merge and release the fix for this: https://github.com/auth0-extensions/auth0-source-control-extension-tools/pull/8

**Comment by mostekcm** [comment]
@xurei this is now fixed in version 1.0.4 on npm

**Comment by andreasgrimm** [comment]
@mostekcm 	with the current version (2.2.5) it's back: Return code is always 0 - even in case of error.

Is this as intended or should it be able to fail builds etc. ?

**Comment by stevezau** [comment]
@andreasgrimm it should return non 0. Can you raise a new issue and ill look into it.

**Comment by adrian-skybaker** [comment]
I still see this issue, have opened https://github.com/auth0/auth0-deploy-cli/issues/272
